# Generated by Django 5.2.7 on 2026-02-13 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead_management', '0010_remove_lead_management_capacity_required_and_more'),
        ('product_management', '0005_alter_productinventory_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('thank_you_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='lead_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mathadi_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotation.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationHighSideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.productvariant')),
                ('quotation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_side_items', to='quotation.quotationversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quotationversion',
            constraint=models.UniqueConstraint(fields=('quotation', 'version_no'), name='unique_quotation_version'),
        ),
    ]
