# Generated by Django 5.2.7 on 2026-06-11 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_alter_sitemanagement_owner_contact_and_more'),
        ('inventory', '0019_alter_purchaseorder_branch'),
        ('lead_management', '0018_customer_gst_customer_pan'),
        ('product_management', '0012_alter_productmodel_phase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('thank_you_note', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='api.branchmanagement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='lead_management.customer')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='api.sitemanagement')),
                ('terms_conditions', models.ManyToManyField(blank=True, related_name='quotations', to='inventory.termsconditions')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('gst_type', models.CharField(choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST')], default='CGST_SGST', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotation.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationLowSideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('mathadi_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.item')),
                ('quotation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_side_items', to='quotation.quotationversion')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationHighSideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('mathadi_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.productvariant')),
                ('quotation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_side_items', to='quotation.quotationversion')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('subcategory', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('MATERIAL', 'Material Based'), ('LABOR', 'Labor Only')], default='LABOR', max_length=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('labor_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sequence', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, to='product_management.item')),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuotationServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mathadi_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transportation_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='quotation.quotationversion')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.servicemaster')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quotationversion',
            constraint=models.UniqueConstraint(fields=('quotation', 'version_no'), name='unique_quotation_version'),
        ),
    ]
