# Generated by Django 5.2.7 on 2026-07-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='declaration',
            field=models.TextField(default='We declare that this quotation shows the actual price for the services.'),
        ),
    ]
