# Generated by Django 5.2.7 on 2026-02-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationversion',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='gst_type',
            field=models.CharField(choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST')], default='CGST_SGST', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
