# Generated by Django 5.2.7 on 2026-07-13 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_staff_profile_fields'),
        ('inventory', '0021_deliverychallan_destination_and_partner_fields'),
        ('product_management', '0012_alter_productmodel_phase'),
        ('quotation', '0002_quotation_declaration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationhighsideitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='quotationversion',
            name='mathadi_charges',
        ),
        migrations.RemoveField(
            model_name='quotationversion',
            name='transportation_charges',
        ),
        migrations.AddField(
            model_name='quotation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='api.branchmanagement'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='api.sitemanagement'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='terms_conditions',
            field=models.ManyToManyField(blank=True, related_name='quotations', to='inventory.termsconditions'),
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='mathadi_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='total_with_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='transportation_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='unit',
            field=models.CharField(default='NOS', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='gst_type',
            field=models.CharField(choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST')], default='CGST_SGST', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='thank_you_note',
            field=models.TextField(default=0.0, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotationversion',
            name='version_no',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='QuotationLowSideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('mathadi_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.item')),
                ('quotation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_side_items', to='quotation.quotationversion')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('MATERIAL', 'Material Based'), ('LABOR', 'Labor Only')], default='LABOR', max_length=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('labor_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sequence', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, to='product_management.item')),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuotationServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mathadi_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transportation_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='quotation.quotationversion')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.servicemaster')),
            ],
        ),
    ]
