# Generated by Django 5.2.7 on 2026-02-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_quotationversion_grand_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationversion',
            name='mathadi_charges',
        ),
        migrations.RemoveField(
            model_name='quotationversion',
            name='transportation_charges',
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='mathadi_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='transportation_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationlowsideitem',
            name='mathadi_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
