# Generated by Django 5.2.7 on 2026-07-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_remove_quotationhighsideitem_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationversion',
            name='gst_type',
            field=models.CharField(choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST'), ('NO_GST', 'No GST')], default='CGST_SGST', max_length=20),
        ),
    ]
