# Generated by Django 5.2.7 on 2026-02-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_remove_quotationversion_mathadi_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationhighsideitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='quotationlowsideitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='total_with_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationlowsideitem',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationlowsideitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationlowsideitem',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotationlowsideitem',
            name='total_with_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
