# Generated by Django 5.2.7 on 2026-02-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_remove_quotationhighsideitem_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationversion',
            name='high_side_gst_amount',
        ),
        migrations.RemoveField(
            model_name='quotationversion',
            name='high_side_subtotal',
        ),
        migrations.RemoveField(
            model_name='quotationversion',
            name='high_side_total_amount',
        ),
        migrations.RemoveField(
            model_name='quotationversion',
            name='low_side_gst_amount',
        ),
        migrations.RemoveField(
            model_name='quotationversion',
            name='low_side_gst_percent',
        ),
        migrations.RemoveField(
            model_name='quotationversion',
            name='low_side_subtotal',
        ),
        migrations.RemoveField(
            model_name='quotationversion',
            name='low_side_total_amount',
        ),
    ]
