# Generated by Django 5.2.7 on 2026-02-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_remove_quotationversion_high_side_gst_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationversion',
            name='version_no',
            field=models.CharField(max_length=100),
        ),
    ]
