# Generated by Django 5.2.7 on 2026-03-13 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_branchmanagement_pincode'),
        ('inventory', '0009_purchaseorder_note'),
        ('quotation', '0007_alter_quotationversion_version_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='api.branchmanagement'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='api.sitemanagement'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='terms_conditions',
            field=models.ManyToManyField(blank=True, related_name='quotations', to='inventory.termsconditions'),
        ),
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationlowsideitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
