# Generated by Django 5.2.7 on 2026-03-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_quotation_branch_quotation_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='unit',
            field=models.CharField(default='NOS', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationlowsideitem',
            name='unit',
            field=models.CharField(default='NOS', max_length=20),
        ),
    ]
