# Generated by Django 5.2.7 on 2026-03-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0009_quotationhighsideitem_unit_quotationlowsideitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationhighsideitem',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationlowsideitem',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
