# Generated by Django 5.2.7 on 2026-04-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0010_quotationhighsideitem_hsn_sac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='thank_you_note',
            field=models.TextField(default='Thank you for your enquiry. We look forward to doing business with you.', max_length=400),
            preserve_default=False,
        ),
    ]
