# Generated by Django 5.2.7 on 2026-06-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0012_alter_productmodel_phase'),
        ('quotation', '0012_servicecategory_servicemaster_quotationserviceitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemaster',
            name='item',
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Link to existing items from Item Master (for material-based services)', to='product_management.item'),
        ),
    ]
