# Generated by Django 5.2.7 on 2026-02-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_role_alter_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_contact', models.CharField(max_length=20)),
                ('secondary_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('state_code', models.CharField(max_length=20)),
                ('gst_no', models.CharField(blank=True, max_length=255, null=True)),
                ('is_head_office', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SiteManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site_shortcut', models.CharField(blank=True, max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_contact', models.CharField(max_length=20)),
            ],
        ),
    ]
