# Generated by Django 5.2.7 on 2026-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_branchmanagement_sitemanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmanagement',
            name='company_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branchmanagement',
            name='msme_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
