# Generated by Django 5.2.7 on 2026-03-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_branchmanagement_company_pan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmanagement',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
