# Generated by Django 5.2.7 on 2026-03-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_branchmanagement_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemanagement',
            name='owner_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitemanagement',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
