# Generated by Django 5.2.7 on 2026-07-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_staff_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('select_permission', models.BooleanField(default=False)),
                ('read_permission', models.BooleanField(default=True)),
                ('write_permission', models.BooleanField(default=False)),
                ('create_permission', models.BooleanField(default=False)),
                ('delete_permission', models.BooleanField(default=False)),
                ('print_permission', models.BooleanField(default=False)),
                ('email_permission', models.BooleanField(default=False)),
                ('report_permission', models.BooleanField(default=False)),
                ('import_permission', models.BooleanField(default=False)),
                ('export_permission', models.BooleanField(default=False)),
                ('share_permission', models.BooleanField(default=False)),
                ('only_if_creator', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.role')),
            ],
            options={
                'ordering': ['document_type', 'role__name'],
                'unique_together': {('role', 'document_type', 'level')},
            },
        ),
    ]
