# Generated by Django 5.2.7 on 2026-07-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='modify_all_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='view_all_permission',
            field=models.BooleanField(default=False),
        ),
    ]
