# Generated by Django 5.2.13 on 2026-08-29 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=500)),
                ('cc', models.CharField(blank=True, max_length=500, null=True)),
                ('bcc', models.CharField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('document_type', models.CharField(choices=[('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase Order'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('document_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
