# Generated by Django 5.2.13 on 2026-08-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=20)),
                ('category', models.CharField(choices=[('LEADS', 'Leads / Enquiries'), ('QUOTATIONS', 'Quotations'), ('INVOICES', 'Invoices'), ('PURCHASE_ORDERS', 'Purchase Orders')], default='QUOTATIONS', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
