# Generated by Django 5.2.7 on 2026-01-15 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=200)),
                ('phase', models.CharField(max_length=20)),
                ('inverter', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ac_sub_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_model', to='product_management.acsubtypes')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_model', to='product_management.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('star_rating', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_management.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('IN_STOCK', 'IN_STOCK'), ('SOLD', 'SOLD'), ('DAMAGED', 'DAMAGED')], default='IN_STOCK', max_length=20)),
                ('warehouse', models.CharField(max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='product_management.productvariant')),
            ],
        ),
    ]
