# Generated by Django 5.2.7 on 2026-01-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_productmodel_productvariant_productinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='capacity',
            field=models.CharField(max_length=50),
        ),
    ]
