# Generated by Django 5.2.7 on 2026-01-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_alter_productvariant_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='warehouse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
