# Generated by Django 5.2.7 on 2026-02-16 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_remove_productvariant_price_productmodel_is_part_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feature_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='item_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='item_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='material_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('size_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('thickness', models.CharField(blank=True, max_length=50, null=True)),
                ('thickness_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('density', models.CharField(blank=True, max_length=50, null=True)),
                ('density_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_management.brand')),
                ('feature_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_management.feature_type')),
                ('item_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_management.item_class')),
                ('item_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_management.item_type')),
                ('material_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_management.material_type')),
            ],
        ),
    ]
