# Generated by Django 5.2.7 on 2026-03-09 19:42
# Generated by Django 5.2.7 on 2026-03-10 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0007_feature_type_item_class_item_type_material_type_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='feature_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_management.feature_type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_management.item_class'),
        ),
    ]
