# Generated by Django 5.2.7 on 2026-03-13 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0008_alter_item_feature_type_id_alter_item_item_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature_type',
            name='shortcut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item_class',
            name='shortcut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item_type',
            name='shortcut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='material_type',
            name='shortcut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_management.brand'),
        ),
    ]
