# Generated by Django 5.2.7 on 2026-03-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0009_feature_type_shortcut_item_class_shortcut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='product_management.actype')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_materials', to='product_management.item')),
            ],
            options={
                'unique_together': {('ac_type', 'material')},
            },
        ),
    ]
