# Generated by Django 5.2.7 on 2026-04-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0010_acmaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
