# Generated by Django 5.2.7 on 2026-04-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0011_productvariant_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='phase',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
