# Generated by Django 5.2.7 on 2025-12-03 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('both_address_is_same', models.BooleanField(default=False)),
                ('site_address', models.TextField(blank=True, null=True)),
                ('site_city', models.CharField(blank=True, max_length=100, null=True)),
                ('site_state', models.CharField(blank=True, max_length=100, null=True)),
                ('site_pin_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lead_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements_details', models.TextField(blank=True)),
                ('hvac_application', models.CharField(blank=True, max_length=200)),
                ('capacity_required', models.CharField(blank=True, max_length=200)),
                ('lead_source', models.CharField(choices=[('google_ads', 'Google Ads'), ('indiamart', 'IndiaMART'), ('bni', 'BNI')], max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in-process', 'In-Process')], max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assignment', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='lead_management.customer')),
            ],
        ),
    ]
