# Generated by Django 5.2.7 on 2025-12-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='lead_source',
            field=models.CharField(choices=[('google_ads', 'Google Ads'), ('indiamart', 'IndiaMART'), ('bni', 'BNI'), ('other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_process', 'In Process')], max_length=200),
        ),
    ]
