# Generated by Django 5.2.7 on 2025-12-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0004_leadfaq_leadfollowup_leadfollowupfaqanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='land_line_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='poc_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='poc_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
