# Generated by Django 5.2.7 on 2025-12-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0005_customer_land_line_no_customer_poc_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='project_adderess',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
