# Generated by Django 5.2.7 on 2025-12-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0007_customer_secondary_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='lead_source',
            field=models.CharField(max_length=200),
        ),
    ]
