# Generated by Django 5.2.7 on 2026-01-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0008_alter_lead_management_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='enquiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='lead_source_input',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
