# Generated by Django 5.2.7 on 2026-01-19 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0009_lead_management_enquiry_date_and_more'),
        ('product_management', '0004_alter_productvariant_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead_management',
            name='capacity_required',
        ),
        migrations.RemoveField(
            model_name='lead_management',
            name='hvac_application',
        ),
        migrations.CreateModel(
            name='lead_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ac_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.acsubtypes')),
                ('ac_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.actype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.brand')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_products', to='lead_management.lead_management')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.productmodel')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.productvariant')),
            ],
        ),
    ]
