# Generated by Django 5.2.7 on 2026-02-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0010_remove_lead_management_capacity_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='is_service_lead',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='lead_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
