# Generated by Django 5.2.7 on 2026-02-12 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0011_lead_management_is_service_lead_and_more'),
        ('product_management', '0005_alter_productinventory_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFollowUpProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ac_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.acsubtypes')),
                ('ac_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.actype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.brand')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lead_management.leadfollowup')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.productmodel')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.productvariant')),
            ],
        ),
    ]
