# Generated by Django 5.2.7 on 2026-03-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0012_leadfollowupproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead_management',
            name='referance_by',
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='contact_person_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='service_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='is_service_lead',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
