# Generated by Django 5.2.7 on 2026-03-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0013_remove_lead_management_referance_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='lead_source_input',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
