# Generated by Django 5.2.7 on 2026-03-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0014_alter_lead_management_lead_source_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='is_service_lead',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('service', 'Service'), ('both', 'Both')], max_length=20, null=True),
        ),
    ]
