# Generated by Django 5.2.7 on 2026-03-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0015_alter_lead_management_is_service_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='service_type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
