# Generated by Django 5.2.7 on 2026-03-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0016_alter_lead_management_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
