# Generated by Django 5.2.7 on 2026-03-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0017_alter_customer_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gst',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
