# Generated by Django 5.2.7 on 2026-06-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0018_customer_gst_customer_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='is_qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='qualifying_answers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
