# Generated by Django 5.2.7 on 2026-02-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('office_address', models.TextField()),
                ('gst_details', models.CharField(max_length=15)),
                ('office_poc_name', models.CharField(max_length=100)),
                ('office_poc_phone', models.CharField(max_length=15)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('store_address', models.TextField(blank=True, null=True)),
                ('supplier_category', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_details', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('store_poc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_poc_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
