# Generated by Django 5.2.7 on 2026-02-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_branchmanagement_sitemanagement'),
        ('product_management', '0007_feature_type_item_class_item_type_material_type_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsConditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('office_address', models.TextField()),
                ('gst_details', models.CharField(max_length=15)),
                ('office_poc_name', models.CharField(max_length=100)),
                ('office_poc_phone', models.CharField(max_length=15)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('store_address', models.TextField(blank=True, null=True)),
                ('supplier_category', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_details', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('store_poc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_poc_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(max_length=10)),
                ('purchase_order_no', models.CharField(max_length=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('quotation_ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('quotation_date', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='api.branchmanagement')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='api.sitemanagement')),
                ('terms_conditions', models.ManyToManyField(blank=True, related_name='purchase_orders', to='inventory.termsconditions')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.vendor')),
            ],
            options={
                'unique_together': {('purchase_order_no', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uom', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_management.item')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_management.productvariant')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.purchaseorder')),
            ],
        ),
        migrations.AddField(
            model_name='termsconditions',
            name='terms_condition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='inventory.termsconditiontype'),
        ),
    ]
