# Generated by Django 5.2.7 on 2026-02-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaseorder_po_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='office_poc_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='office_poc_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
