# Generated by Django 5.2.7 on 2026-03-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_purchaseorder_round_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
