# Generated by Django 5.2.7 on 2026-03-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchaseorder_delivery_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='delivery_address',
            new_name='delivery_destination',
        ),
    ]
