# Generated by Django 5.2.7 on 2026-03-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_delivery_address_purchaseorder_delivery_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsconditiontype',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
