# Generated by Django 5.2.7 on 2026-03-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_termsconditiontype_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
