# Generated by Django 5.2.7 on 2026-03-16 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sitemanagement_owner_contact_and_more'),
        ('inventory', '0009_purchaseorder_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='api.branchmanagement'),
        ),
    ]
