# Generated by Django 5.2.7 on 2026-03-31 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_purchaseorder_branch'),
        ('product_management', '0010_acmaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_date', models.DateField(blank=True, null=True)),
                ('grn_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='inventory.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='GRNProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.grn')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_management.item')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_management.productvariant')),
                ('purchase_order_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.purchaseorderproduct')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uom', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_management.item')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_management.productvariant')),
            ],
            options={
                'unique_together': {('product_variant', 'item')},
            },
        ),
    ]
