# Generated by Django 5.2.7 on 2026-04-02 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_materialissue_materialissueitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=50, unique=True)),
                ('return_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='inventory.materialissue')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_issue_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.materialissueitem')),
                ('material_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.materialreturn')),
            ],
        ),
    ]
