# Generated by Django 5.2.7 on 2026-04-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_vendor_email'),
        ('inventory', '0014_materialreturn_materialreturnitem'),
    ]

    operations = [
    ]
