# Generated by Django 5.2.7 on 2026-04-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_merge_20260407_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialreturn',
            name='return_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
