# Generated by Django 5.2.7 on 2026-05-18 11:48

import django.db.models.deletion
from django.db import migrations, models


def set_default_branch(apps, schema_editor):
    """Set the first branch as default for existing POs with NULL branch"""
    PurchaseOrder = apps.get_model('inventory', 'PurchaseOrder')
    BranchManagement = apps.get_model('api', 'BranchManagement')
    
    # Get the first branch
    first_branch = BranchManagement.objects.first()
    
    if first_branch:
        # Update all POs with NULL branch to use the first branch
        PurchaseOrder.objects.filter(branch__isnull=True).update(branch=first_branch)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sitemanagement_owner_contact_and_more'),
        ('inventory', '0018_populate_in_out_quantities'),
    ]

    operations = [
        # First, populate NULL branches with the first branch
        migrations.RunPython(set_default_branch, reverse_code=migrations.RunPython.noop),
        
        # Then make the field required
        migrations.AlterField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='purchase_orders', 
                to='api.branchmanagement'
            ),
        ),
    ]
