# Generated by Django 5.2.7 on 2026-06-25 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_purchaseorder_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('dispatch_date', models.DateField()),
                ('transporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_proof', models.FileField(blank=True, null=True, upload_to='delivery_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challans', to='inventory.materialissue')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.deliverychallan')),
                ('material_issue_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.materialissueitem')),
            ],
        ),
    ]
