# Generated by Django 5.2.7 on 2026-06-22 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0019_alter_purchaseorder_branch'),
        ('lead_management', '0018_customer_gst_customer_pan'),
        ('product_management', '0012_alter_productmodel_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package_type', models.CharField(choices=[('COMPREHENSIVE', 'Comprehensive Service'), ('NON_COMPREHENSIVE', 'Non-Comprehensive Service')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('annual_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_visits_per_year', models.IntegerField(default=4)),
                ('parts_replacement_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('response_time_hours', models.IntegerField(default=24)),
                ('includes_emergency_calls', models.BooleanField(default=True)),
                ('emergency_call_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AMCContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('sale_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('amc_start_date', models.DateField()),
                ('amc_end_date', models.DateField()),
                ('amc_included_in_sale', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('amc_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_renewal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amc_contracts', to='lead_management.customer')),
                ('previous_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.amccontract')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_management.productvariant')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amc.amcpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AMCRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField()),
                ('renewal_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RENEWED', 'Renewed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from', to='amc.amccontract')),
                ('previous_contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='renewal', to='amc.amccontract')),
            ],
        ),
        migrations.CreateModel(
            name='AMCService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('SCHEDULED', 'Scheduled Maintenance'), ('EMERGENCY', 'Emergency Repair'), ('FOLLOW_UP', 'Follow-up Visit')], max_length=20)),
                ('visit_date', models.DateField()),
                ('engineer_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_reported', models.TextField()),
                ('work_performed', models.TextField()),
                ('is_billable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PENDING_PARTS', 'Pending Parts')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amc_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='amc.amccontract')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='AMCInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('parts_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial Payment'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='amc.amcservice')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='AMCServiceLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=100)),
                ('labor_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_labor_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('include_in_customer_invoice', models.BooleanField(default=False)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labor', to='amc.amcservice')),
            ],
        ),
        migrations.CreateModel(
            name='AMCServiceParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(default=1)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('include_in_customer_invoice', models.BooleanField(default=False)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='amc.amcservice')),
            ],
        ),
    ]
