# Generated by Django 5.2.7 on 2026-06-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amcservice',
            name='issue_reported',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amcservice',
            name='work_performed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
