# Generated by Django 5.2.7 on 2026-07-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_servicemanagementrecord_servicemanagementmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemanagementrecord',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
