# Generated by Django 5.2.7 on 2026-07-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0009_technicianworkrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianworkrecord',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
