# Generated by Django 5.2.7 on 2026-09-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0015_amcservicevisit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='renewal_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='contract_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='amccontract',
            unique_together={('contract_number', 'version')},
        ),
    ]
