# Generated by Django 5.2.7 on 2026-03-10 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead_management', '0012_leadfollowupproduct'),
        ('product_management', '0008_alter_item_feature_type_id_alter_item_item_class_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('gstin', models.CharField(max_length=50)),
                ('pan', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=255)),
                ('declaration', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_address', models.TextField()),
                ('buyer_gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_state', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('ship_to_address', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_gstin', models.CharField(max_length=50)),
                ('company_pan', models.CharField(max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_msme_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=255)),
                ('declaration', models.TextField(blank=True, null=True)),
                ('delivery_note', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_note_date', models.DateField(blank=True, null=True)),
                ('supplier_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('other_references', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatch_doc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatched_through', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('terms_of_payment', models.CharField(blank=True, max_length=255, null=True)),
                ('terms_of_delivery', models.TextField(blank=True, null=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('work_description', models.TextField(blank=True, null=True)),
                ('gst_type', models.CharField(choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST')], max_length=20)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_in_words', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='lead_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='HighSideInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('hsn_sac', models.CharField(max_length=50)),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.productvariant')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_side_items', to='invoice.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='LowSideInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_side_items', to='invoice.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.item')),
            ],
        ),
    ]
