# Generated by Django 5.2.7 on 2026-02-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_msme_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
