# Generated by Django 5.2.7 on 2026-03-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_branchmanagement_company_pan_and_more'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company_gstin',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company_msme_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company_pan',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branchmanagement'),
        ),
    ]
