# Generated by Django 5.2.7 on 2026-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_purchaseorder_round_off'),
        ('invoice', '0002_remove_invoice_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='terms_conditions',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='inventory.termsconditions'),
        ),
    ]
