# Generated by Django 5.2.7 on 2026-03-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_terms_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='gst_type',
            field=models.CharField(choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST'), ('NO_GST', 'No GST')], default='CGST_SGST', max_length=20),
        ),
    ]
