# Generated by Django 5.2.7 on 2026-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_gst_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_note_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Note Date'),
        ),
    ]
