# Generated by Django 5.2.7 on 2026-03-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_branchmanagement_company_pan_and_more'),
        ('invoice', '0005_alter_invoice_delivery_note_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='site_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='api.sitemanagement'),
        ),
    ]
