# Generated by Django 5.2.7 on 2026-03-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_invoice_site_name_invoice_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='terms_of_delivery',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='terms_of_payment',
        ),
    ]
