# Generated by Django 5.2.7 on 2026-03-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_remove_invoice_terms_of_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer_dated',
            field=models.DateField(blank=True, null=True, verbose_name='Buyer Order Date'),
        ),
    ]
