# Generated by Django 5.2.7 on 2026-03-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoice_buyer_dated'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
