# Generated by Django 5.2.7 on 2026-03-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoice_gst_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowsideinvoiceitem',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='highsideinvoiceitem',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
