# Generated by Django 5.2.7 on 2026-04-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_lowsideinvoiceitem_hsn_sac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='buyer_gstin',
            field=models.CharField(default=0.0, max_length=20),
            preserve_default=False,
        ),
    ]
