# Generated by Django 5.2.7 on 2026-05-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_invoice_buyer_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_chalan_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
