# Generated by Django 5.2.7 on 2026-07-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_invoice_delivery_chalan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='buyer_gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
